FROM shaojintian/beego_blog_v1:latest

MAINTAINER shaojintian

WORKDIR /go/src/beego_blog_v1

COPY ./* /go/src/beego_blog_v1/

#RUN go build main.go







#docker build -t beego_blog_v1:v0.2 .

##blog
#docker run  -it  --name beego -p 8080:8080 beego_blog_v1:v0.2 /bin/bash

## mysql
#docker run  -d  --name mysql  -p 3306:3306 -e MYSQL_ROOT_PASSWORD=6963038 mysql
# docker exec -it mysql /bin/bash
